services:
    chris1278.extonoff.controller.acp:
        class: chris1278\extonoff\controller\acp_controller
        arguments:
            - '@ext.manager' 
            - '@request'
            - '@language'
            - '@config'
            - '@template'
            - '@dbal.conn'
            - '@log'
            - '@user'
            - '@cache.driver'
    chris1278.extonoff.listener:
        class: chris1278\extonoff\event\acp_listener
        arguments:
            - '@template'
            - '@config'
            - '@service_container'
        tags:
            - { name: event.listener }
